tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: ACCOUNTADMIN
      database: DEV_DWDB
      schema: PUBLIC
      warehouse: COMPUTE_WH
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: ACCOUNTADMIN
      database: PROD_DWDB
      schema: PUBLIC
      warehouse: COMPUTE_WH